 
version: '3'
services:
  gretel:
    build:
      context: server 
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow
    links:
      - mongodb
  
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
      TZ: Europe/Moscow
    volumes:
      - ./mongodb/data:/data/db
