version: '3.8'

secrets:
  gretel_config:
    file: gretel_config

services:
  gretel:
    build:
      context: ..
      dockerfile: docker/gretel.Dockerfile
    restart: unless-stopped
    secrets:
      - gretel_config
    environment:
      TZ: Europe/Moscow
    links:
      - mongodb
  
  mongodb:
    image: mongo:5.0
    restart: unless-stopped
    environment:
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
      TZ: Europe/Moscow
    volumes:
      - ../mongodb/data:/data/db
