version: '3.8'

secrets:
  gretel_config:
    file: gretel_config
  doxa_ovd_config:
    file: doxa_ovd_config
  doxa_bot_config:
    file: doxa_bot_config

services:
  gretel:
    build:
      context: ..
      dockerfile: docker/gretel.Dockerfile
    restart: unless-stopped
    secrets:
      - gretel_config
    environment:
      TZ: Europe/Moscow
    links:
      - gretel_db

  gretel_db:
    image: mongo:5.0
    restart: unless-stopped
    environment:
      MONGODB_DATA_DIR: /data/gretel_db
      MONDODB_LOG_DIR: /dev/null
      TZ: Europe/Moscow
    volumes:
      - ../db/gretel/data:/data/db

  doxa_bot:
    build:
      context: ..
      dockerfile: docker/doxa_bot.Dockerfile
    restart: unless-stopped
    secrets:
      - doxa_bot_config
    environment:
      TZ: Europe/Moscow
    links:
      - doxa_bot_db

  doxa_bot_db:
    image: mongo:5.0
    restart: unless-stopped
    environment:
      MONGODB_DATA_DIR: /data/doxa_bot_db
      MONDODB_LOG_DIR: /dev/null
      TZ: Europe/Moscow
    volumes:
      - ../db/doxa_bot/data:/data/db

  doxa_ovd:
    build:
      context: ..
      dockerfile: docker/doxa_ovd.Dockerfile
    restart: unless-stopped
    secrets:
      - doxa_ovd_config
    environment:
      TZ: Europe/Moscow
    links:
      - doxa_ovd_db

  doxa_ovd_db:
    image: mongo:5.0
    restart: unless-stopped
    environment:
      MONGODB_DATA_DIR: /data/doxa_ovd_db
      MONDODB_LOG_DIR: /dev/null
      TZ: Europe/Moscow
    volumes:
      - ../db/doxa_ovd/data:/data/db
